Feat crawl subreddit
deltakapp/products-from-reddit pull request #8
Opened 2023-02-09 22:00 UTC by deltakapp

## What does this Pull Request Do?
Addresses issue #7: implements crawl command
- core functionality is in crawl.py while parsing is handled in crawl click command
- crawl.fetch_posts() is versatile for other use cases
- posts are received from reddit api in batches, converted to pandas dataframe for filtration, and saved to individual json files in data/ directory

## Manual Test Cases
- Verified functionality for crawl command with and without start option
- Verified error response for start option which is in future

## Acceptance Criteria
- [X] Implement secrets approach for configuring sensitive credentials
  - [X] Make sure credentials cannot be committed to the repo!
- [X] Create method to iterate through /r/hardwareswap posts sorted by new
- [X] Create _save_reddit_post method
  - implemented as save_posts_to_json because reddit api returns posts in batches
  - currently json files are not formatted for human friendliness

### Core
- [X] Functionality for new code verified for: 
  - [X] happy-path (expected scenarios)
  - [X] non-happy-path (error handling scenarios)
- ~[ ] All unit tests passing~
- ~[ ] Unit tests were added/updated~
    - Unit testing has not yet been implemented

### Documentation
- [X] Code comments added
- [X] Typehints filled out
- [X] Docstrings added for non-trivial functions

### Misc.
- ~[ ] Code style passed linters~
    - Linting not yet implemented
- [X] Checked spelling in filenames, method names, code comments
- [X] Dependencies were pinned to specific versions (or version ranges) as appropriate

2023-02-13 02:00 UTC, ErinMyLungs requested changes
This looks really excellent!

After applying the minor bug fix, the crawl worked and dumped the post data as expected.

Most of the feedback is type hints and docstring formatting nit-picks which aren't a huge thing.

The two main changes needed are:

1. Updating the option type for the start date to use the `click.types.DateTime()` param type
2. Updating the `full_crawl` method to break the while loop if the `fetched` dataframe is empty

2023-02-13 02:00 UTC, ErinMyLungs commented on main.py
> +@click.option('--start', help = 'specify past timestamp to crawl posts to')
[Type spec] Click does actually implement a datetime type - it's the last one listed right before the `Parameter Names` section [here](https://click.palletsprojects.com/en/8.1.x/parameters/#parameter-types).

The updated option decorator would be:

```python
@click.option(
    "--start",
    help="specify past timestamp to crawl posts to",
    type=click.types.DateTime(),
)
```

On a more general dev-ex/ergonomics point, taking input as a UTC timestamp is tough because you have to convert your date into a long number. I'm a huge fan of the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format of `2023-02-13` which can be easily parsed by python via

```python
from datetime import datetime
print(datetime.fromisoformat("2023-02-13"))
```

This change would allow the crawl script to be invoked with a start date like: `python main.py --start 2022-01-01` instead of `python main.py --start 1641024000`.

2023-02-13 02:00 UTC, ErinMyLungs commented on crawl.py
> +  "writes posts to separate json files in data/ directory"
[Nit] Docstrings on functions use the triple quote string format and should typically be capitalized.

```suggestion
  "Writes posts to separate json files in data/ directory."
```

2023-02-13 02:00 UTC, ErinMyLungs commented on crawl.py
> +def save_posts_to_json(posts):
[Nit] Missing type hints for this function.

This should be 
```suggestion
def save_posts_to_json(posts: pd.DataFrame):
```

You can spec the return type as `-> None` but often I skip that because it feels verbose and isn't really helpful IMO.

2023-02-13 02:00 UTC, ErinMyLungs commented on crawl.py
> +  """fetches # of posts, starting at page reference"""
[Nit] Missing return typehint and docstring could be clearer.

```suggestion
def fetch_posts(number: int = 3, page: str = None) -> Tuple[pd.DataFrame, Optional[str]]:
    """Fetches the number of posts starting at the page reference.

    Args:
      number: Max number of posts to fetch from API.
      page: The string ID of the page to fetch from reddit

    Returns: Dataframe of reddit posts from the given page and the next page ID if more posts exist on the next page.
    """
 ```
     
For the type hinting, `Optional` means the returned value can either be a `str` type or `None`.
    
`Tuple` and `Optional` in the code above need to be imported from the `typing` module ([python stdlib docs](https://docs.python.org/3.9/library/typing.html))
    
 ```python
    from typing import Tuple, Optional
```

2023-02-13 02:00 UTC, ErinMyLungs commented on crawl.py
> +    incomplete = last_index_time >= start_time
[Bug] when running the crawler, this part crashes for me after 1k posts because `fetched` returns a 0 row dataframe and trying to use iloc throws an index out of bounds error

<details>
<summary> Traceback of error encountered:</summary>

```python
Traceback (most recent call last):
  File "/home/erin/PycharmProjects/products-from-reddit/main.py", line 54, in <module>
    cli()
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/erin/PycharmProjects/products-from-reddit/main.py", line 39, in crawl
    full_crawl(start)
  File "/home/erin/PycharmProjects/products-from-reddit/crawl.py", line 78, in full_crawl
    last_index_time = datetime.utcfromtimestamp(fetched.iloc[-1]["created_utc"])
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/pandas/core/indexing.py", line 1073, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/pandas/core/indexing.py", line 1625, in _getitem_axis
    self._validate_integer(key, axis)
  File "/home/erin/PycharmProjects/products-from-reddit/venv/lib/python3.9/site-packages/pandas/core/indexing.py", line 1557, in _validate_integer
    raise IndexError("single positional indexer is out-of-bounds")
IndexError: single positional indexer is out-of-bounds
```
</details>

We can fix this by explicitly checking for the fetched dataframe being empty before running this code:

```python
        if fetched.empty:
            assert (
                next_page is None
            ), f"Fetched posts returned an empty dataframe but we were given a " \
               f"next page ID {next_page}. Crawler might need debugging."
            break
```

The assertion here is a technique that I'm a big fan of. If the `fetched` dataframe is empty we expect that we're at the end of the crawl and we should not have a `next_page` ID and it should always be `None`. If for some reason that is wrong, then there might be a problem with our crawler code and this assert will crash it.

I can talk with you about this more when we get together tomorrow, it can be a great way to validate your assumptions about a system are holding true instead of having weird bugs crop up.

2023-02-13 02:00 UTC, ErinMyLungs commented on crawl.py
> +  "fetches all posts within specified duration"
[Docstring nit] Needs triple quote and slight formatting tweak

```suggestion
  """Fetches all posts within specified duration, saving posts to disk"""
```

2023-02-13 02:00 UTC, ErinMyLungs commented on main.py
> +  "Fetch posts within specified timeframe"
[Docstring nit] Triple quote fix again

```suggestion
  """Fetch posts within specified timeframe"""
```

2023-02-13 02:00 UTC, ErinMyLungs commented on main.py
> +      return
[Toast] This is excellent! Validating your input makes sense and stopping the program if it violates expectations is a great habit.

No change for this, just wanted to celebrate this

2023-02-14 00:37 UTC, ErinMyLungs commented on main.py
> +      return
```python
raise click.BadOptionUsage("Error: start must be before present time")
```

2023-02-14 01:41 UTC, deltakapp commented on crawl.py
> +    incomplete = last_index_time >= start_time
I was not able to reproduce bug. I managed to get 1000 posts with next_page = none, which is the behavior expected of the reddit API. The bug must be some more specific edge case. At any rate, I'll add the assertion to catch this case.

2023-02-14 03:26 UTC, ErinMyLungs commented on main.py
> +    start = datetime.fromisoformat(str(start))
[Nit] This conversion is no longer needed as specifying the `type=click.types.DateTime()` automatically converts the start date to a `datetime` object.

2023-02-14 03:34 UTC, ErinMyLungs approved these changes

2023-02-14 03:35 UTC, merged